require("sontt")
require("sontt.plugins.telescope")
require("sontt.plugins.lsp")
require("sontt.plugins.nvim-cmp")
require("sontt.plugins.flutter-tool")
-- require("sontt.plugins.nvim-tree")
require("sontt.plugins.toggleterm")
require("sontt.plugins.treesitter")
require("sontt.plugins.treesitter-context")
require("sontt.plugins.harpoon")
require("sontt.plugins.lualine")
require("sontt.plugins.fugitive")
require("sontt.plugins.obsidian")
require("sontt.plugins.oil")
require("sontt.plugins.gp")
require("sontt.plugins.dapui")
require("sontt.plugins.nvim-dap")
require("sontt.plugins.avante")
-- require("sontt.plugins.noice")
require("sontt.plugins.telescope-live-grep-args")
