require("sontt")
require("sontt.plugins.telescope")
require("sontt.plugins.lsp")
require("sontt.plugins.nvim-cmp")
-- require("sontt.plugins.flutter-tool")
require("sontt.plugins.nvim-tree")
require("sontt.plugins.toggleterm")
require("sontt.plugins.treesitter")
require("sontt.plugins.treesitter-context")
require("sontt.plugins.harpoon")
require("sontt.plugins.lualine")

require("sontt.autocmds.execute_dart")
require("sontt.autocmds.execute_c_plus_plus")
